In [ ]:
import pandas as pd
pd.set_option("display.precision", 2)

In [ ]:
df = pd.read_excel("data/finance_data.xlsx")
df.head()

,Indicator Name,2019-01-01 00:00:00,2019-02-01 00:00:00,2019-03-01 00:00:00,2019-04-01 00:00:00,2019-05-01 00:00:00,2019-06-01 00:00:00,2019-07-01 00:00:00,2019-08-01 00:00:00,2019-09-01 00:00:00,...,2020-03-01 00:00:00,2020-04-01 00:00:00,2020-05-01 00:00:00,2020-06-01 00:00:00,2020-07-01 00:00:00,2020-08-01 00:00:00,2020-09-01 00:00:00,2020-10-01 00:00:00,2020-11-01 00:00:00,2020-12-01 00:00:00
0,Income,450100.0,480000.0,430000.0,510000.0,480000.0,520000.0,510000.0,410000.0,520000.0,...,390016.83,540105.33,540076.39,429146.94,526718.78,388866.87,570927.51,533815.66,587532.93,364365.58
1,Cost of Goods Sold,125000.0,125900.0,125500.0,125200.0,123500.0,124200.0,122600.0,123700.0,126200.0,...,119240.84,120577.23,134958.81,98794.93,113362.02,143013.19,98736.71,139155.84,107095.10,114962.93
2,Gross Profit,325100.0,354100.0,304500.0,384800.0,356500.0,395800.0,387400.0,286300.0,393800.0,...,371875.20,365917.80,437916.48,462854.25,332885.68,254913.80,424986.04,308642.93,288165.27,290575.23
3,Total Operating Expenses,175100.0,180000.0,178500.0,172200.0,174400.0,175100.0,179400.0,185000.0,200200.0,...,216234.46,204051.99,209801.90,148910.94,224082.56,176715.74,241426.29,155486.15,167105.95,135130.14
4,Operating Profit (EBIT),150000.0,174100.0,126000.0,212600.0,182100.0,220700.0,208000.0,101300.0,193600.0,...,107348.65,231388.84,219719.23,188990.84,184295.34,100185.00,191770.18,237650.61,217087.16,165070.59

In [ ]:
df_transposed = df.set_index("Indicator Name").transpose().reset_index(names=["Date"])
df_transposed.rename_axis(None, axis=1, inplace=True)
df_transposed.tail()

,Date,Income,Cost of Goods Sold,Gross Profit,Total Operating Expenses,Operating Profit (EBIT),Taxes,Net Profit,Net Profit Margin %,Expenses,Cash at EOM,Quick Ratio,Current Ratio,Accounts Receivable,Accounts Payable
19,2020-08-01,388866.87,143013.19,254913.80,176715.74,100185.00,87952.72,12232.28,0.03,319728.94,539227.55,0.92,4.00,115440.42,100096.16
20,2020-09-01,570927.51,98736.71,424986.04,241426.29,191770.18,112911.44,78858.74,0.14,340163.00,366759.34,1.11,3.10,111628.12,85752.45
21,2020-10-01,533815.66,139155.84,308642.93,155486.15,237650.61,92990.06,144660.56,0.27,294641.98,549228.17,1.75,3.12,97795.25,82201.67
22,2020-11-01,587532.93,107095.10,288165.27,167105.95,217087.16,100114.13,116973.02,0.20,274201.05,532654.53,1.74,4.35,123453.93,81709.49
23,2020-12-01,364365.58,114962.93,290575.23,135130.14,165070.59,100067.10,65003.49,0.18,250093.07,568674.30,1.50,3.06,124390.24,97212.28

In [ ]:
# Drop Monthly Financial Ratio
df_transposed["Date"] = pd.to_datetime(df_transposed['Date'])

In [ ]:
df_transposed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        24 non-null     datetime64[ns]
 1   Income                      24 non-null     float64
 2   Cost of Goods Sold          24 non-null     float64
 3   Gross Profit                24 non-null     float64
 4   Total Operating Expenses    24 non-null     float64
 5   Operating Profit (EBIT)     24 non-null     float64
 6   Taxes                       24 non-null     float64
 7   Net Profit                  24 non-null     float64
 8   Net Profit Margin %         24 non-null     float64
 9   Expenses                    24 non-null     float64
 10  Cash at EOM                 24 non-null     float64
 11  Quick Ratio                 24 non-null     float64
 12  Current Ratio               24 non-null     float64
 13  Accounts Receivable         24 non-null     float64
 14  Accounts Payable            24 non-null     float64
dtypes: datetime64[ns](1), float64(14)
memory usage: 2.9 KB

In [ ]:
df_transposed.to_csv("data/finance_data_clean")